# Generated by Django 4.1.4 on 2023-01-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('proceso', models.CharField(max_length=80)),
                ('servicio', models.CharField(max_length=80)),
                ('ans', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bitacora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numerobit', models.CharField(max_length=40)),
                ('asignedto', models.CharField(max_length=50)),
                ('dateini', models.DateField(auto_now_add=True)),
                ('datefin', models.DateField()),
                ('compañia', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('id_area', models.CharField(max_length=40)),
            ],
        ),
    ]
