# Generated by Django 4.1.4 on 2023-02-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbitacoras', '0002_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='UsuarioBit',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
